// source: pnp/application/v1/config.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.pnp.application.v1.Config', null, global);
goog.exportSymbol('proto.pnp.application.v1.GetConfigRequest', null, global);
goog.exportSymbol('proto.pnp.application.v1.PlatformType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pnp.application.v1.GetConfigRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pnp.application.v1.GetConfigRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pnp.application.v1.GetConfigRequest.displayName = 'proto.pnp.application.v1.GetConfigRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pnp.application.v1.Config = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pnp.application.v1.Config, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pnp.application.v1.Config.displayName = 'proto.pnp.application.v1.Config';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pnp.application.v1.GetConfigRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.pnp.application.v1.GetConfigRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pnp.application.v1.GetConfigRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pnp.application.v1.GetConfigRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    platform: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pnp.application.v1.GetConfigRequest}
 */
proto.pnp.application.v1.GetConfigRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pnp.application.v1.GetConfigRequest;
  return proto.pnp.application.v1.GetConfigRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pnp.application.v1.GetConfigRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pnp.application.v1.GetConfigRequest}
 */
proto.pnp.application.v1.GetConfigRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.pnp.application.v1.PlatformType} */ (reader.readEnum());
      msg.setPlatform(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pnp.application.v1.GetConfigRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pnp.application.v1.GetConfigRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pnp.application.v1.GetConfigRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pnp.application.v1.GetConfigRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlatform();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * optional PlatformType platform = 1;
 * @return {!proto.pnp.application.v1.PlatformType}
 */
proto.pnp.application.v1.GetConfigRequest.prototype.getPlatform = function() {
  return /** @type {!proto.pnp.application.v1.PlatformType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.pnp.application.v1.PlatformType} value
 * @return {!proto.pnp.application.v1.GetConfigRequest} returns this
 */
proto.pnp.application.v1.GetConfigRequest.prototype.setPlatform = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pnp.application.v1.Config.prototype.toObject = function(opt_includeInstance) {
  return proto.pnp.application.v1.Config.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pnp.application.v1.Config} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pnp.application.v1.Config.toObject = function(includeInstance, msg) {
  var f, obj = {
    country: jspb.Message.getFieldWithDefault(msg, 1, ""),
    region: jspb.Message.getFieldWithDefault(msg, 2, ""),
    zone: jspb.Message.getFieldWithDefault(msg, 3, ""),
    currency: jspb.Message.getFieldWithDefault(msg, 4, ""),
    minimumVersion: jspb.Message.getFieldWithDefault(msg, 5, ""),
    latestVersion: jspb.Message.getFieldWithDefault(msg, 6, ""),
    latestTermsDate: (f = msg.getLatestTermsDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    promptAcceptTerms: jspb.Message.getBooleanFieldWithDefault(msg, 32, false),
    promptMarketingEmail: jspb.Message.getBooleanFieldWithDefault(msg, 33, false),
    enableNameSuggestion: jspb.Message.getBooleanFieldWithDefault(msg, 34, false),
    enableHomePageEmailCapture: jspb.Message.getBooleanFieldWithDefault(msg, 35, false),
    enableHomePageFreeVideo: jspb.Message.getBooleanFieldWithDefault(msg, 36, false),
    enableGameAnsweringMachine: jspb.Message.getBooleanFieldWithDefault(msg, 37, false),
    liveChatIdEn: jspb.Message.getFieldWithDefault(msg, 64, 0),
    liveChatIdEs: jspb.Message.getFieldWithDefault(msg, 65, 0),
    liveChatIdFr: jspb.Message.getFieldWithDefault(msg, 66, 0),
    liveChatIdIt: jspb.Message.getFieldWithDefault(msg, 67, 0),
    singleRecipientFormId: jspb.Message.getFieldWithDefault(msg, 68, 0),
    groupRecipientFormId: jspb.Message.getFieldWithDefault(msg, 69, 0),
    certificateName: jspb.Message.getFieldWithDefault(msg, 96, ""),
    freeVideoScenarioCode: jspb.Message.getFieldWithDefault(msg, 97, ""),
    freeVideoFormId: jspb.Message.getFieldWithDefault(msg, 98, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pnp.application.v1.Config}
 */
proto.pnp.application.v1.Config.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pnp.application.v1.Config;
  return proto.pnp.application.v1.Config.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pnp.application.v1.Config} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pnp.application.v1.Config}
 */
proto.pnp.application.v1.Config.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCountry(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRegion(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setZone(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurrency(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMinimumVersion(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setLatestVersion(value);
      break;
    case 7:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setLatestTermsDate(value);
      break;
    case 32:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPromptAcceptTerms(value);
      break;
    case 33:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPromptMarketingEmail(value);
      break;
    case 34:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnableNameSuggestion(value);
      break;
    case 35:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnableHomePageEmailCapture(value);
      break;
    case 36:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnableHomePageFreeVideo(value);
      break;
    case 37:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnableGameAnsweringMachine(value);
      break;
    case 64:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLiveChatIdEn(value);
      break;
    case 65:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLiveChatIdEs(value);
      break;
    case 66:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLiveChatIdFr(value);
      break;
    case 67:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLiveChatIdIt(value);
      break;
    case 68:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSingleRecipientFormId(value);
      break;
    case 69:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setGroupRecipientFormId(value);
      break;
    case 96:
      var value = /** @type {string} */ (reader.readString());
      msg.setCertificateName(value);
      break;
    case 97:
      var value = /** @type {string} */ (reader.readString());
      msg.setFreeVideoScenarioCode(value);
      break;
    case 98:
      var value = /** @type {string} */ (reader.readString());
      msg.setFreeVideoFormId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pnp.application.v1.Config.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pnp.application.v1.Config.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pnp.application.v1.Config} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pnp.application.v1.Config.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCountry();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRegion();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getZone();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCurrency();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMinimumVersion();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getLatestVersion();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getLatestTermsDate();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getPromptAcceptTerms();
  if (f) {
    writer.writeBool(
      32,
      f
    );
  }
  f = message.getPromptMarketingEmail();
  if (f) {
    writer.writeBool(
      33,
      f
    );
  }
  f = message.getEnableNameSuggestion();
  if (f) {
    writer.writeBool(
      34,
      f
    );
  }
  f = message.getEnableHomePageEmailCapture();
  if (f) {
    writer.writeBool(
      35,
      f
    );
  }
  f = message.getEnableHomePageFreeVideo();
  if (f) {
    writer.writeBool(
      36,
      f
    );
  }
  f = message.getEnableGameAnsweringMachine();
  if (f) {
    writer.writeBool(
      37,
      f
    );
  }
  f = message.getLiveChatIdEn();
  if (f !== 0) {
    writer.writeUint32(
      64,
      f
    );
  }
  f = message.getLiveChatIdEs();
  if (f !== 0) {
    writer.writeUint32(
      65,
      f
    );
  }
  f = message.getLiveChatIdFr();
  if (f !== 0) {
    writer.writeUint32(
      66,
      f
    );
  }
  f = message.getLiveChatIdIt();
  if (f !== 0) {
    writer.writeUint32(
      67,
      f
    );
  }
  f = message.getSingleRecipientFormId();
  if (f !== 0) {
    writer.writeUint32(
      68,
      f
    );
  }
  f = message.getGroupRecipientFormId();
  if (f !== 0) {
    writer.writeUint32(
      69,
      f
    );
  }
  f = message.getCertificateName();
  if (f.length > 0) {
    writer.writeString(
      96,
      f
    );
  }
  f = message.getFreeVideoScenarioCode();
  if (f.length > 0) {
    writer.writeString(
      97,
      f
    );
  }
  f = message.getFreeVideoFormId();
  if (f.length > 0) {
    writer.writeString(
      98,
      f
    );
  }
};


/**
 * optional string country = 1;
 * @return {string}
 */
proto.pnp.application.v1.Config.prototype.getCountry = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.setCountry = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string region = 2;
 * @return {string}
 */
proto.pnp.application.v1.Config.prototype.getRegion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.setRegion = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string zone = 3;
 * @return {string}
 */
proto.pnp.application.v1.Config.prototype.getZone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.setZone = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string currency = 4;
 * @return {string}
 */
proto.pnp.application.v1.Config.prototype.getCurrency = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.setCurrency = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string minimum_version = 5;
 * @return {string}
 */
proto.pnp.application.v1.Config.prototype.getMinimumVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.setMinimumVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string latest_version = 6;
 * @return {string}
 */
proto.pnp.application.v1.Config.prototype.getLatestVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.setLatestVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional google.protobuf.Timestamp latest_terms_date = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.pnp.application.v1.Config.prototype.getLatestTermsDate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 7));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.pnp.application.v1.Config} returns this
*/
proto.pnp.application.v1.Config.prototype.setLatestTermsDate = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.clearLatestTermsDate = function() {
  return this.setLatestTermsDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.pnp.application.v1.Config.prototype.hasLatestTermsDate = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional bool prompt_accept_terms = 32;
 * @return {boolean}
 */
proto.pnp.application.v1.Config.prototype.getPromptAcceptTerms = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 32, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.setPromptAcceptTerms = function(value) {
  return jspb.Message.setProto3BooleanField(this, 32, value);
};


/**
 * optional bool prompt_marketing_email = 33;
 * @return {boolean}
 */
proto.pnp.application.v1.Config.prototype.getPromptMarketingEmail = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 33, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.setPromptMarketingEmail = function(value) {
  return jspb.Message.setProto3BooleanField(this, 33, value);
};


/**
 * optional bool enable_name_suggestion = 34;
 * @return {boolean}
 */
proto.pnp.application.v1.Config.prototype.getEnableNameSuggestion = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 34, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.setEnableNameSuggestion = function(value) {
  return jspb.Message.setProto3BooleanField(this, 34, value);
};


/**
 * optional bool enable_home_page_email_capture = 35;
 * @return {boolean}
 */
proto.pnp.application.v1.Config.prototype.getEnableHomePageEmailCapture = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 35, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.setEnableHomePageEmailCapture = function(value) {
  return jspb.Message.setProto3BooleanField(this, 35, value);
};


/**
 * optional bool enable_home_page_free_video = 36;
 * @return {boolean}
 */
proto.pnp.application.v1.Config.prototype.getEnableHomePageFreeVideo = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 36, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.setEnableHomePageFreeVideo = function(value) {
  return jspb.Message.setProto3BooleanField(this, 36, value);
};


/**
 * optional bool enable_game_answering_machine = 37;
 * @return {boolean}
 */
proto.pnp.application.v1.Config.prototype.getEnableGameAnsweringMachine = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 37, false));
};


/**
 * @param {boolean} value
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.setEnableGameAnsweringMachine = function(value) {
  return jspb.Message.setProto3BooleanField(this, 37, value);
};


/**
 * optional uint32 live_chat_id_en = 64;
 * @return {number}
 */
proto.pnp.application.v1.Config.prototype.getLiveChatIdEn = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 64, 0));
};


/**
 * @param {number} value
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.setLiveChatIdEn = function(value) {
  return jspb.Message.setProto3IntField(this, 64, value);
};


/**
 * optional uint32 live_chat_id_es = 65;
 * @return {number}
 */
proto.pnp.application.v1.Config.prototype.getLiveChatIdEs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 65, 0));
};


/**
 * @param {number} value
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.setLiveChatIdEs = function(value) {
  return jspb.Message.setProto3IntField(this, 65, value);
};


/**
 * optional uint32 live_chat_id_fr = 66;
 * @return {number}
 */
proto.pnp.application.v1.Config.prototype.getLiveChatIdFr = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 66, 0));
};


/**
 * @param {number} value
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.setLiveChatIdFr = function(value) {
  return jspb.Message.setProto3IntField(this, 66, value);
};


/**
 * optional uint32 live_chat_id_it = 67;
 * @return {number}
 */
proto.pnp.application.v1.Config.prototype.getLiveChatIdIt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 67, 0));
};


/**
 * @param {number} value
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.setLiveChatIdIt = function(value) {
  return jspb.Message.setProto3IntField(this, 67, value);
};


/**
 * optional uint32 single_recipient_form_id = 68;
 * @return {number}
 */
proto.pnp.application.v1.Config.prototype.getSingleRecipientFormId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 68, 0));
};


/**
 * @param {number} value
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.setSingleRecipientFormId = function(value) {
  return jspb.Message.setProto3IntField(this, 68, value);
};


/**
 * optional uint32 group_recipient_form_id = 69;
 * @return {number}
 */
proto.pnp.application.v1.Config.prototype.getGroupRecipientFormId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 69, 0));
};


/**
 * @param {number} value
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.setGroupRecipientFormId = function(value) {
  return jspb.Message.setProto3IntField(this, 69, value);
};


/**
 * optional string certificate_name = 96;
 * @return {string}
 */
proto.pnp.application.v1.Config.prototype.getCertificateName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 96, ""));
};


/**
 * @param {string} value
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.setCertificateName = function(value) {
  return jspb.Message.setProto3StringField(this, 96, value);
};


/**
 * optional string free_video_scenario_code = 97;
 * @return {string}
 */
proto.pnp.application.v1.Config.prototype.getFreeVideoScenarioCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 97, ""));
};


/**
 * @param {string} value
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.setFreeVideoScenarioCode = function(value) {
  return jspb.Message.setProto3StringField(this, 97, value);
};


/**
 * optional string free_video_form_id = 98;
 * @return {string}
 */
proto.pnp.application.v1.Config.prototype.getFreeVideoFormId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 98, ""));
};


/**
 * @param {string} value
 * @return {!proto.pnp.application.v1.Config} returns this
 */
proto.pnp.application.v1.Config.prototype.setFreeVideoFormId = function(value) {
  return jspb.Message.setProto3StringField(this, 98, value);
};


/**
 * @enum {number}
 */
proto.pnp.application.v1.PlatformType = {
  ANDROID: 0,
  IOS: 1,
  MACOS: 2,
  TVOS: 3,
  WEB: 4
};

goog.object.extend(exports, proto.pnp.application.v1);
